site_name: datality_admin
site_description: -
repo_url: https://github.com/lkulbacki/datality-admin-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/lkulbacki">lkulbacki</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
